### ISSUE TITLE
There are RT tickets

### ISSUE THREAD

**Issue by eserte** [ziali088/jsonapi-document#2]
Please see https://rt.cpan.org/Ticket/Display.html?id=124454

**Comment by ziali088** [comment]
Hi @eserte, thanks for the report!

I've tested that it consistently breaks on version 0.49 of Test::DBIx::Class, have pinned the version required to 0.52.

**Comment by ziali088** [comment]
Version 0.3 is the pinned version, I'll close this if you're happy

**Comment by eserte** [comment]
Yes, looks good: http://fast-matrix.cpantesters.org/?dist=JSONAPI-Document%200.3
